export const gamesData = [
  {
    name: "God of War",
    description: "Kratos, has travelled to the Norse land to live a mundane life. But a strange visitor sets in motion a journey of epic proportions.",
    year: "2018",
    likes: 0,
    dislikes: 0,
    reviews: [""],
  },
  {
    name: "Darksiders I",
    description: "The apocalypse started prematurely. Your mission is to unravel the mistery as to why.",
    year: "2010",
    likes: 0,
    dislikes: 0,
    reviews: [""],
  },
  {
    name: "Darksiders II",
    description: "Death wants to clean his brothers name, but first it needs to travel to distant realms to get to the truth.",
    year: "2011",
    likes: 0,
    dislikes: 0,
    reviews: [""],
  },
  {
    name: "Darksiders III",
    description: "Fury is sent to earth to hunt down the seven deadly sins.",
    year: "2018",
    likes: 0,
    dislikes: 0,
    reviews: [""],
  },
  {
    name: "Cuphead",
    description: "Cuphead is a 2d boss rush mode game.",
    year: "2017",
    likes: 0,
    dislikes: 0,
    reviews: [""],
  },
  {
    name: "Castlevania: Circle of the Moon",
    description: "Explore Dracula's castle and end his dark reign of terror.",
    year: "2001",
    likes: 0,
    dislikes: 0,
    reviews: [""],
  },
  {
    name: "Outriders",
    description: "Shoot your way across a new planet and gather new gear using different abilities.",
    year: "2021",
    likes: 0,
    dislikes: 0,
    reviews: [""],
  },
  {
    name: "Darksouls",
    description: "Prepare to die.",
    year: "2009",
    likes: 0,
    dislikes: 0,
    reviews: [""],
  },
  {
    name: "Streets of Rage 4",
    description: "Old school beat em up with new cell shaded graphics.",
    year: "2021",
    likes: 0,
    dislikes: 0,
    reviews: [""],
  },
  {
    name: "Marvel's Spider-Man",
    description: "Play as Spider-Man in this new epic adventure.",
    year: "2018",
    likes: 0,
    dislikes: 0,
    reviews: [""],
  },
];